#!/usr/bin/env python3
"""
Newyes LD0806 — Windows Image Printer (self-contained)

Sends pre-encoded print data to the printer over USB.
The .bin file is generated by tools/print_image.py on macOS.

Usage:
    python windows_print_image.py <packet_file.bin>
"""

import ctypes
import ctypes.wintypes as wt
import time
import sys
import struct

DEVICE_PATH = r'\\?\USB#VID_2E88&PID_6001#Printer_123456#{28d78fad-5a12-11d1-ae5b-0000f803a8c2}'


def main():
    if len(sys.argv) < 2:
        print("Usage: python windows_print_image.py <packet_file.bin>")
        sys.exit(1)

    bin_path = sys.argv[1]
    data = open(bin_path, 'rb').read()
    off = 0
    n_pkts = struct.unpack_from('<I', data, off)[0]
    off += 4
    packets = []
    for _ in range(n_pkts):
        plen = struct.unpack_from('<I', data, off)[0]
        off += 4
        packets.append(data[off:off + plen])
        off += plen
    print(f"Loaded {n_pkts} packets from {bin_path} ({len(data)} bytes)")

    k32 = ctypes.windll.kernel32
    handle = k32.CreateFileW(DEVICE_PATH, 0xC0000000, 3, None, 3, 0, None)
    if handle == -1:
        err = k32.GetLastError()
        print(f"Failed to open printer: error {err}")
        print("Is the printer connected via USB and powered on?")
        sys.exit(1)
    print("Printer connected.\n")

    written = wt.DWORD(0)
    buf = ctypes.create_string_buffer(512)
    read_n = wt.DWORD(0)

    for i, pkt in enumerate(packets):
        k32.WriteFile(handle, pkt, len(pkt), ctypes.byref(written), None)
        wait = 2.0 if len(pkt) > 10000 else 0.5
        time.sleep(wait)
        k32.ReadFile(handle, buf, 512, ctypes.byref(read_n), None)
        ack = "ack" if read_n.value > 0 else "no ack"
        print(f"  [{i + 1}/{n_pkts}] {len(pkt):>6d} bytes  {ack}")
        k32.SetLastError(0)

    k32.CloseHandle(handle)
    print("\nDone!")


if __name__ == '__main__':
    main()
